apiVersion: v1
entries:
  dagster:
  - apiVersion: v1
    created: "2021-01-14T10:51:01.500210546-08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.helm.sh/stable
      version: 6.16.3
    description: Dagster is a system for building modern data applications.
    digest: 2028f05ce9a6e6a263a9a4fbac4e4a07a13c9edf83bb69db5f93991f5126c934
    icon: https://raw.githubusercontent.com/dagster-io/dagster/master/assets/Dagster.png
    name: dagster
    urls:
    - release/dagster-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2021-01-14T10:51:01.493377136-08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.helm.sh/stable
      version: 6.16.3
    description: Dagster is a system for building modern data applications.
    digest: 6b24be54b20ffe4e8caae2cd837a3aec160b634631618945c560de65610ca3f4
    icon: https://raw.githubusercontent.com/dagster-io/dagster/master/assets/Dagster.png
    name: dagster
    urls:
    - release/dagster-0.1.0.tgz
    version: 0.1.0
generated: "2021-01-14T10:51:01.486995518-08:00"
