apiVersion: v1
entries:
  dagster:
  - apiVersion: v1
    created: "2021-02-26T15:07:31.318051397-08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.helm.sh/stable
      version: 6.16.3
    - condition: redis.enabled, not redis.external
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 6.0.10
    description: Dagster is a system for building modern data applications.
    digest: 28004462bd1288266abd55603ffa9ad55210104ae243bc8a2562d7f56365bfe2
    icon: https://raw.githubusercontent.com/dagster-io/dagster/master/assets/Dagster.png
    name: dagster
    urls:
    - release/dagster-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    created: "2021-02-26T15:07:31.308436275-08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.helm.sh/stable
      version: 6.16.3
    description: Dagster is a system for building modern data applications.
    digest: f2bbc9e818d0c0f4ed899e4d61856106f9c0af060ac94cf9073cea521ade3657
    icon: https://raw.githubusercontent.com/dagster-io/dagster/master/assets/Dagster.png
    name: dagster
    urls:
    - release/dagster-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: "2021-02-26T15:07:31.302182247-08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.helm.sh/stable
      version: 6.16.3
    description: Dagster is a system for building modern data applications.
    digest: 2028f05ce9a6e6a263a9a4fbac4e4a07a13c9edf83bb69db5f93991f5126c934
    icon: https://raw.githubusercontent.com/dagster-io/dagster/master/assets/Dagster.png
    name: dagster
    urls:
    - release/dagster-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2021-02-26T15:07:31.296790621-08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.helm.sh/stable
      version: 6.16.3
    description: Dagster is a system for building modern data applications.
    digest: 6b24be54b20ffe4e8caae2cd837a3aec160b634631618945c560de65610ca3f4
    icon: https://raw.githubusercontent.com/dagster-io/dagster/master/assets/Dagster.png
    name: dagster
    urls:
    - release/dagster-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-26T15:07:31.290455723-08:00"
